### ISSUE TITLE
what is "rawseeds_ros"?

### ISSUE THREAD

**Issue by caotangyu** [cogsys-tuebingen/cslibs_mapping#1]
where could i download the test bag ? The rawseeds_ros pkg could not be found on the internet,is it private?

**Comment by c-schulz** [comment]
Hi @will1991,
yes, the rawseeds_ros pkg is a private package. It consists of scripts related to the [Rawseeds Indoor Dataset](http://www.rawseeds.org/rs/datasets/view//6). You can find information about the relative pose of the sensors and about the data format in the [Deliverable D2.1](http://www.rawseeds.org/home/2009/03/18/deliverable-d21-raw-data-indoor/).
However, the provided launch file is only intended as an example and it should be possible to adapt it to any other suitable bag file containing laser or pointcloud data.

**Comment by will1991** [comment]
> Hi @will1991,
> yes, the rawseeds_ros pkg is a private package. It consists of scripts related to the [Rawseeds Indoor Dataset](http://www.rawseeds.org/rs/datasets/view//6). You can find information about the relative pose of the sensors and about the data format in the [Deliverable D2.1](http://www.rawseeds.org/home/2009/03/18/deliverable-d21-raw-data-indoor/).
> However, the provided launch file is only intended as an example and it should be possible to adapt it to any other suitable bag file containing laser or pointcloud data.

**Comment by caotangyu** [comment]
Thanks ! @c-schulz

**Comment by c-schulz** [comment]
Hi @will1991,
a new example launch file and test data is available now.
