### ISSUE TITLE
test_bag??

### ISSUE THREAD

**Issue by LLplane** [cogsys-tuebingen/cslibs_mapping#2]
Hi,
your code looks very nice,but do you have some rosbags for testing? I hope that some rosbags about 2D would be published on this depository. Thanks very much!

**Comment by c-schulz** [comment]
Hi @LLplane,
I will search for a small bagfile with ground truth trajectory next week.

**Comment by LLplane** [comment]
Waiting for you,Thanks very much!

**Comment by c-schulz** [comment]
Hi @LLplane,
please use the script provided in the `bag` folder to download the data.
In the `launch` folder, there is also a new launch file.
Please also note that there will be further changes to the `cslibs_ndt` dependency in the near future.
