### ISSUE TITLE
can't create map 

### ISSUE THREAD

**Issue by iceuw** [cogsys-tuebingen/cslibs_mapping#3]
Hello, thanks for your awesome jobs. I have met a problem when using the bag to create the OccupancyNDTGridMapper2D map.  
In my first try, my program stopped at function "process(queue_.pop())" in 184 line mapper.hpp. Then , I copy the content in "process()" function in  "occupancy_ndt_grid_mapper_2d.h" to another new funtion  "test()" (this funtion is added by myself) and change the "process" to "test",  then the program can normally enter in the function "test()'. But this time it stop at "lookfortransform" again.
After I print the tf message in bag file, I found there is no tf from the laser frame ("/front/laser") to the map_frame(/odom). The two frame are in two independent tf group. 

Has the launch file any problem? Or has I missed some configure?

**Comment by c-schulz** [comment]
Hey,
this is probably related to the problem that the transformation between "/base_link" and "/base_footprint" is published as static transformation and only at the beginning of the bagfile. Can you try starting the launch file without the 'rosbag play' node and afterwards starting the bagfile separately from another terminal, after the mapping node was set up completely? This way, the mapping node should be able to listen to all static transformations. 
By the way, if you want to work with ONDT maps, there will hopefully be some improvements in the near future.

**Comment by iceuw** [comment]
Thanks a lot! I realized that I have played the bag files with no param "--clock". 
After I comment the rosbag node in the launch file, and run "rosbag play --clock --rate 1.0 -k example.bag" in another terminal. The program can launch rightly!
